import type { Metadata } from "next";
import { Manrope, Poppins } from "next/font/google";
import "@/styles/globals.css";

const headingFont = Poppins({
	variable: "--font-heading",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});
const bodyFont = Manrope({
	variable: "--font-body",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="dark">
			<body
				className={`${headingFont.variable} ${bodyFont.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
