import type { Metadata } from "next";
import { Navbar, Footer, Modal } from "@/components";
import { Manrope } from "next/font/google";
import { MenuProvider } from "@/context/MenuContext";
import "./globals.css";

export const metadata: Metadata = {
	title: "Freelancer | Designer | Developer",
	description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const manrope = Manrope({
	subsets: ["latin"],
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={manrope.className}>
				<MenuProvider>
					<Navbar />
					<main >{children}</main>
					<Footer />
					<Modal />
				</MenuProvider>
			</body>
		</html>
	);
}
