import { Navbar, Footer, Modal } from "@/components";
import { Manrope } from "next/font/google";
import { MenuProvider } from "@/context/MenuContext";
import "./globals.css";
// import '@unocss/reset/tailwind.css'
import { ModalProvider } from "@/context/ModalContext";

export const metadata = {
	title: "Freelancer | Designer | Developer",
	description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const manrope = Manrope({
	subsets: ["latin"],
	display: "swap",
});

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={manrope.className}
				suppressHydrationWarning={true}
			>
				<Navbar />
				<main>{children}</main>
				<Footer />
				<Modal />
			</body>
		</html>
	);
}
