export {default as Hero} from './Hero'
export {default as About} from './About'
export {default as Gallery} from './Gallery'
export {default as SelectedWork} from './Selected Work'
export {default as ClientsReviews} from './ClientsReviews'
export {default as Products} from './Products'